# Generated by Django 5.0.6 on 2024-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='traveler_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_traveler',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_traveler_companion',
            field=models.CharField(default=''),
        ),
    ]
