# Generated by Django 5.0.6 on 2024-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_ride_id_remove_user_traveler_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_traveler',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_traveler_companion',
            field=models.CharField(null=True),
        ),
    ]
