# Generated by Django 5.0.6 on 2024-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_traveler',
            field=models.JSONField(default=dict),
        ),
    ]
