# Generated by Django 5.0.6 on 2024-06-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_traveler',
        ),
    ]
