# Generated by Django 5.0.6 on 2024-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_is_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='traveler_id',
        ),
        migrations.AddField(
            model_name='user',
            name='is_traveler',
            field=models.CharField(null=True),
        ),
    ]
