# Generated by Django 5.0.6 on 2024-06-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_ride_id_user_traveler_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='traveler_id',
        ),
    ]
