# Generated by Django 5.0.6 on 2024-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_ride_id_user_traveler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_location',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
