# Generated by Django 5.0.6 on 2024-06-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_end_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
