# Generated by Django 5.0.6 on 2024-06-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_time',
        ),
    ]
