# Generated by Django 5.0.6 on 2024-06-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_end_time_remove_ride_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='start_location',
            new_name='current_location',
        ),
    ]
